### PR TITLE
Create the ec2 playbook to launch a new server

### PR DESCRIPTION
**Pull request by pachr**
We are going to create a new playbook to be able to launch a new EC2 server.

#### 1. Create the playbook `launch_new_servers.yml`
  - [x] 1.1 Provide the key name
  - [x] 1.2 For the first build, choose a default AWS AMI
  - [x] 1.3 Other parameters will be set on Jenkins as extra vars
  - [x] 1.4 call the ec2 role
  - [x] 1.5 Give the possibility to pass a provision playbook, for the first build we can pass `base.yml` (see #1 )

#### 2. Create the ec2 role
  - [x] 2.1 Spin up the instance
  - [x] 2.2 Add the host to a temporary host group
  - [x] 2.3 Tag instance
  - [x] 2.4 Attach the additional volume 
  - [x] 2.5 Possibility to attach a second extra volume (it's an option, we need to pass an extra variable)
  - [x] 2.6 Wait 1 minute  the instance to be ready

#### 3. first build
  - [x] 3.1 Build with a default AWS AMI
  - [x] 3.2 Run the base playbook as a provision one
  - [x] 3.3 When it's finished, snap the volume
  - [x] 3.4 Create an image with this volume

#### 4. For other build
  - [x] 4.1 We will use the new AMI

#### 5. Dependencies

- [x] 5.1 Create a new AWS private key (.pem)
- [x] 5.2 We will need the AWS access key and AWS secret key for Jenkins
- [x] 5.3 Which AMI are we going to use for markets to build the first time?

### CODE REVIEW

**Comment by pachr** [comment]
@remitaffin At the end of the description, you will find a list of dependencies that I need to finish this role. Can you provide me them? Please

**Comment by remitaffin** [comment]
@darwinyc has all this information for the dependencies.

**Comment by remitaffin** [comment]
Actually I can provide you that.
- The key pair for AWS will be "Markets-IT"
- I sent you the AWS access key and secret key for itmarkets user
- We don't have the AMI yet...

**Comment by darwinyc** [comment]
The ami is running and I just need to snap it. 

Darwin Abella
VP of IT | The Noodle Companies, LLC

**Comment by pachr** [comment]
@darwinyc could you provide me the name of this ami? if you have it, to complete my script.

**Comment by remitaffin** [comment]
Why is the base role inside this PR?

**Comment by remitaffin** [comment]
Good! You can merge it to master!

**Pull request merged**
